### ISSUE TITLE
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.

### ISSUE THREAD

**Issue by dshwei** [zjunlp/AdaKGC#11]
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.

**Comment by dshwei** [comment]
def get_input_tokens(self, bsz, spots, asocs):
        input_tokens = self.prompt_inputs.unsqueeze(0).expand(bsz, -1)**.clone().**to(self.t5.device)
        spots_len = len(spots[0])

        input_tokens[:, 0] = 1
        input_tokens[:, 1] = 2
        input_tokens[:, 2] = 3
        start_pos = 3
        for i, spot in enumerate(spots):
            for j, s in enumerate(spot, start = start_pos):
                input_tokens[i, j] = self.get_prompt_ids(tuple(s))
        input_tokens[:, start_pos + spots_len] = 3

        input_tokens[:, start_pos + 1 + spots_len] = 4
        start_pos = 5 + spots_len
        for i, asoc in enumerate(asocs):
            for j, a in enumerate(asoc, start = start_pos):
                input_tokens[i, j] = self.get_prompt_ids(tuple(a))
        input_tokens[:, 5 + spots_len + len(asocs[0])] = 4

        return input_tokens



self.prompt_inputs.unsqueeze(0).expand(bsz, -1).**clone().**to(self.t5.device)  **要 .clone()**

**Comment by guihonghao** [comment]
感谢你的提醒，我们已对相应的代码进行了修改。

**Comment by zxlzr** [comment]
hi, have you solved  your issue?

**Comment by dshwei** [comment]
修改之后问题解决了，谢谢



发自我的iPhone


------------------ Original ------------------
From: Eric ***@***.***&gt;
Date: Mon,Jan 15,2024 7:18 PM
To: zjunlp/AdaKGC ***@***.***&gt;
Cc: dshwei ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zjunlp/AdaKGC] RuntimeError: unsupported operation: more thanone element of the written-to tensor refers to a single memory location.Please clone() the tensor before performing the operation. (Issue #11)





 
hi, have you solved  your issue?

**Comment by dshwei** [comment]
hi，
代码中的readme文件 中的如下（在所有迭代数据集上的自动推理）脚本中的参数&nbsp;&nbsp;
--model=output/${data_name}_${mode}_${ratio}
确定是设置output 吗？



* 在所有迭代数据集上的自动推理（即`data/iter_1/ace05_event_H`~`data/iter _7/ace05_event_H`）


```bash
mode=H
data_name=ace05_event
task=event
device=0
ratio=0.8
python3 inference_mul.py --dataname=data/${data_name}/${data_name}_${mode} --t5_path=hf_models/mix --model=output/${data_name}_${mode}_${ratio} --task=${task} --cuda=${device} --mode=${mode} --use_prompt --use_ssi --prompt_len=80 --prompt_dim=512
```
`use_ssi`、`use_prompt`、`prompt_len`、`prompt_dim`需要跟训练时保持一致。

**Comment by guihonghao** [comment]
bash scripts/run_prompt.bash --model=hf_models/mix --data=data/${data_name}_${mode}/iter_1 --output=output/${data_name}_${mode}_${ratio} --config=${data_name}.ini --device=${device} --negative_ratio=${ratio} --record2=data/${data_name}_${mode}/iter_7/record.schema训练后保存的模型地址是--output=output/${data_name}_${mode}_${ratio}，因此在推理时也是output

**Comment by dshwei** [comment]
谢谢，看明白了，运行 run_pormpr.sh 脚本默认的都是要train。
请问我在A800上train ace05_event 大概需要多久？
train的过程中有没有可以优化改进的地方

**Comment by dshwei** [comment]
请问你们有没有开源三个数据集（NYT,Few-NERD,ace05-event )训练好的模型权重?

**Comment by guihonghao** [comment]
A800 batch_size设置大一些，应该跑起来很快。

**Comment by dshwei** [comment]
hi,请教一下
def get_negative_samples(l, k):
&nbsp; &nbsp; from thefuzz import fuzz
&nbsp; &nbsp; from gensim.test.utils import datapath, get_tmpfile
&nbsp; &nbsp; from gensim.models import KeyedVectors
&nbsp; &nbsp; from gensim.scripts.glove2word2vec import glove2word2vec
&nbsp; &nbsp; glove_file = datapath('/zjunlp/ghh/.cache/GloVe/glove.6B.300d.txt')
&nbsp; &nbsp; word2vec_glove_file = get_tmpfile("glove.6B.300d.word2vec.txt")
&nbsp; &nbsp; glove2word2vec(glove_file, word2vec_glove_file)
&nbsp; &nbsp; model = KeyedVectors.load_word2vec_format(word2vec_glove_file)




为啥写的是固定的路径？有下载的地址吗

**Comment by guihonghao** [comment]
https://nlp.stanford.edu/data/glove.6B.zip

**Comment by dshwei** [comment]
谢谢，我已经修改过了，建议代码中也修改一下
我在训练 FEW-NERD&nbsp; 的时候出现了这个问题
Token indices sequence length is longer than the specified maximum sequence length for this model (541 &gt; 512). Running this sequence through the model will result in indexing errors



实体识别任务的训练：
# Current path:&nbsp; */AdaKGC
mode=H
data_name=Few-NERD
task=entity
device=0
ratio=0.8
bash scripts/run_prompt.bash --model=hf_models/mix --data=data/${data_name}_${mode}/iter_1 --output=output/${data_name}_${mode}_${ratio} --config=${data_name}.ini --device=${device} --negative_ratio=${ratio} --record2=data/${data_name}_${mode}/iter_7/record.schema

**Comment by guihonghao** [comment]
序列长度超出了最大长度512需要截断。

**Comment by dshwei** [comment]
mode=H
data_name=ace05_event
task=event
device=0
ratio=0.8
python3 inference_mul.py --dataname=data/${data_name}/${data_name}_${mode} --t5_path=hf_models/mix --model=output/${data_name}_${mode}_${ratio} --task=${task} --cuda=${device} --mode=${mode} --use_prompt --use_ssi --prompt_len=80 --prompt_dim=512

执行这个推理过程的时候，出现了F1指标全部为0 的情况，帮忙看一下什么问题
训练的模型权重信息截图如下：

**Comment by dshwei** [comment]
训练 ace05 的日志文件也发给你，在附件中，请查看一下

**Comment by guihonghao** [comment]
看不到截图，你可以加我的微信ghh200002

**Comment by JiaZY2003** [comment]
> 谢谢，我已经修改过了，建议代码中也修改一下
> 我在训练 FEW-NERD&nbsp; 的时候出现了这个问题
> Token indices sequence length is longer than the specified maximum sequence length for this model (541 &gt; 512). Running this sequence through the model will result in indexing errors
> 
> 
> 
> 实体识别任务的训练：
> # Current path:&nbsp; */AdaKGC
> mode=H
> data_name=Few-NERD
> task=entity
> device=0
> ratio=0.8
> bash scripts/run_prompt.bash --model=hf_models/mix --data=data/${data_name}_${mode}/iter_1 --output=output/${data_name}_${mode}_${ratio} --config=${data_name}.ini --device=${device} --negative_ratio=${ratio} --record2=data/${data_name}_${mode}/iter_7/record.schema

您好，想问一下这里这个在512处的截断是如何实现的
