### ISSUE TITLE
HF_DATASETS_CACHE的数据问题

### ISSUE THREAD

**Issue by 569337083** [zjunlp/AdaKGC#6]
在训练时报错：os.environ["HF_DATASETS_CACHE"]的位置不存在，想问一下这个目录的数据（glove.6B.300d.txt）是从网上下载的吗？

**Comment by guihonghao** [comment]
你需要把run_finetune.py中的os.environ["HF_DATASETS_CACHE"] = "/nature/ghh/.cache/huggingface/datasets"替换成自己的路径
