### ISSUE TITLE
trainer.py报错

### ISSUE THREAD

**Issue by 569337083** [zjunlp/AdaKGC#7]
problem:
1、AttributeError: 'ConstraintSeq2SeqPromptTrainer' object has no attribute 'sharded_ddp'；
2、NameError: name 'ShardedDDPOption' is not defined

From:
delay_optimizer_creation = self.sharded_ddp is not None and self.sharded_ddp != ShardedDDPOption.SIMPLE

想问一下这个是什么原因报错，我该如何解决这个报错呢？非常感谢！

**Comment by guihonghao** [comment]
请确保transformers版本==4.9.2

**Comment by 569337083** [comment]
我修改了transformers对版本为==4.9.2，出现了新的问题：
命令：
bash scripts/run_finetune.bash --model=hf_models/t5-v1_1-base --data=data/Few-NERD_H/iter_1 --output=output/Few-NERD --mode=H --device=0 --batch=16
报错：
  File "*/conda/envs/adakgc/lib/python3.8/site-packages/transformers/file_utils.py", line 390, in is_protobuf_available
    if importlib.util.find_spec("google") is None:
  File "*/conda/envs/adakgc/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
非常感谢您的帮助！

**Comment by 569337083** [comment]
以下是我的环境；
accelerate               0.25.0
aiohttp                  3.9.1
aiosignal                1.3.1
async-timeout            4.0.3
attrs                    23.1.0
beautifulsoup4           4.12.2
certifi                  2022.12.7
charset-normalizer       3.0.1
click                    8.1.3
dataclasses              0.6
datasets                 1.9.0
dill                     0.3.6
filelock                 3.9.0
frozenlist               1.4.0
fsspec                   2022.11.0
gensim                   4.3.2
google                   3.0.0
huggingface-hub          0.0.12
idna                     3.4
Jinja2                   3.1.2
joblib                   1.2.0
MarkupSafe               2.1.3
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
networkx                 3.1
nltk                     3.5
numpy                    1.24.1
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
packaging                23.0
pandas                   1.5.2
Pillow                   9.4.0
pip                      23.3.1
protobuf                 3.0.0
psutil                   5.9.6
pyarrow                  10.0.1
pyarrow-hotfix           0.6
python-dateutil          2.8.2
pytz                     2022.7
PyYAML                   6.0
rapidfuzz                3.5.2
regex                    2022.10.31
requests                 2.28.2
sacremoses               0.0.53
safetensors              0.4.1
scipy                    1.10.1
sentencepiece            0.1.99
setuptools               65.6.3
six                      1.16.0
smart-open               6.4.0
soupsieve                2.5
sympy                    1.12
thefuzz                  0.20.0
tokenizers               0.10.1
torch                    1.8.0+cu111
torchaudio               0.8.0
torchmetrics             0.6.2
tqdm                     4.66.1
transformers             4.9.2
triton                   2.1.0
typing_extensions        4.4.0
tzdata                   2023.3
urllib3                  1.26.14
wheel                    0.37.1
xxhash                   3.2.0
yarl                     1.9.4

**Comment by guihonghao** [comment]
将protobuf换成3.20.0试试

**Comment by 569337083** [comment]
已解决，谢谢大佬！
