### ISSUE TITLE
多卡运行报错

### ISSUE THREAD

**Issue by 569337083** [zjunlp/AdaKGC#8]
problem：
在单卡V100 32G上已经可以运行了，由于速度比较慢，想转到3090上进行尝试，单卡现存不够，考虑多卡，在两张3090的卡上运行出现以下报错，我应该怎么做？
command：
bash scripts/run_finetune.bash --model=hf_models/t5-v1_1-base --data=data/Few-NERD_H/iter_1 --output=output/Few-NERD --mode=H --device=0,1 --batch=16
error：
1、IndexError: Caught IndexError in replica 0 on device 0.；
2、IndexError: index 16 is out of bounds for dimension 0 with size 16

**Comment by guihonghao** [comment]
直接在scripts/run_finetune.bash里面设置CUDA_VISIBLE_DEVICES="0,1"，去掉--device=0,1。如果不行就是不支持多卡
。
