### ISSUE TITLE
代码运行后F1值异常

### ISSUE THREAD

**Issue by 569337083** [zjunlp/AdaKGC#9]
我配置了完整的开发环境，并对以下任务进行测试：
任务名称：Relation Extraction Task
指令：
1、. config/prompt_conf/NYT_H.ini  
2、bash scripts/run_finetune.bash --model=hf_models/t5-v1_1-base --data=data/NYT_H/iter_1 --output=output/NYT --mode=H --device=0 --batch=8（修改了batch_size）
最后的测试结果：
12/25/2023 20:29:01 - INFO - __main__ - ***** Test results *****
12/25/2023 20:29:01 - INFO - __main__ - test_asoc-F1 = 92.8138
12/25/2023 20:29:01 - INFO - __main__ - test_asoc-P = 91.96
12/25/2023 20:29:01 - INFO - __main__ - test_asoc-R = 93.6835
12/25/2023 20:29:01 - INFO - __main__ - test_asoc-gold = 4322.0
12/25/2023 20:29:01 - INFO - __main__ - test_asoc-pred = 4403.0
12/25/2023 20:29:01 - INFO - __main__ - test_asoc-tp = 4049.0
12/25/2023 20:29:01 - INFO - __main__ - test_fixed = 1
12/25/2023 20:29:01 - INFO - __main__ - test_gen_len = 32.7888
12/25/2023 20:29:01 - INFO - __main__ - test_gold_tree = 10833
12/25/2023 20:29:01 - INFO - __main__ - test_gold_tree add_bracket = 1
12/25/2023 20:29:01 - INFO - __main__ - test_loss = 0.0562
12/25/2023 20:29:01 - INFO - __main__ - test_ordered-record-F1 = 90.2995
12/25/2023 20:29:01 - INFO - __main__ - test_ordered-record-P = 89.61
12/25/2023 20:29:01 - INFO - __main__ - test_ordered-record-R = 90.9997
12/25/2023 20:29:01 - INFO - __main__ - test_ordered-record-gold = 10833.0
12/25/2023 20:29:01 - INFO - __main__ - test_ordered-record-pred = 11001.0
12/25/2023 20:29:01 - INFO - __main__ - test_ordered-record-tp = 9858.0
12/25/2023 20:29:01 - INFO - __main__ - test_overall-F1 = 187.5559
12/25/2023 20:29:01 - INFO - __main__ - test_pred_tree = 11002
12/25/2023 20:29:01 - INFO - __main__ - test_record-F1 = 91.2613
12/25/2023 20:29:01 - INFO - __main__ - test_record-P = 90.5645
12/25/2023 20:29:01 - INFO - __main__ - test_record-R = 91.969
12/25/2023 20:29:01 - INFO - __main__ - test_record-gold = 10833.0
12/25/2023 20:29:01 - INFO - __main__ - test_record-pred = 11001.0
12/25/2023 20:29:01 - INFO - __main__ - test_record-tp = 9963.0
12/25/2023 20:29:01 - INFO - __main__ - test_runtime = 233.7369
12/25/2023 20:29:01 - INFO - __main__ - test_samples_per_second = 21.392
12/25/2023 20:29:01 - INFO - __main__ - test_spot-F1 = 94.7421
12/25/2023 20:29:01 - INFO - __main__ - test_spot-P = 94.0187
12/25/2023 20:29:01 - INFO - __main__ - test_spot-R = 95.4768
12/25/2023 20:29:01 - INFO - __main__ - test_spot-gold = 10833.0
12/25/2023 20:29:01 - INFO - __main__ - test_spot-pred = 11001.0
12/25/2023 20:29:01 - INFO - __main__ - test_spot-tp = 10343.0
12/25/2023 20:29:01 - INFO - __main__ - test_steps_per_second = 0.672
12/25/2023 20:29:01 - INFO - __main__ - test_well-formed = 5000
想问一下这里面哪个是论文中提到的F1，另外 test_overall-F1 = 187.5559这个值为什么会超过100呢？感谢大佬回复！

**Comment by guihonghao** [comment]
asoc算的是关系，spot算的是实体，overall是两者之和。

**Comment by 569337083** [comment]
对于ACE2005这个数据集，得到的Event Trigger Evt Tri F1 和 Event Argument Evt Arg F1这两个 F1值分别对应的是什么呢？

**Comment by 569337083** [comment]
1、问题：
针对命名实体识别任务，我将训练得到的模型进行二次迭代，得到的F1值全部为0了，这是为什么呢？
2、命令：
. config/prompt_conf/Few-NERD_H.ini    
bash scripts/run_finetune.bash --model=hf_models/t5-v1_1-base --data=data/Few-NERD_H/iter_2 --output=output/Few-NERD --mode=H --device=0 --batch=8
3、结果：
第一次训练得到的结果：
test_asoc-F1 = 0.0
test_asoc-P = 0.0
test_asoc-R = 0.0
test_asoc-gold = 0.0
test_asoc-pred = 0.0
test_asoc-tp = 0.0
test_fixed = 18
test_gen_len = 19.5484
test_gold_tree = 47609
test_gold_tree add_bracket = 17
test_loss = 0.1317
test_ordered-record-F1 = 73.0027
test_ordered-record-P = 70.522
test_ordered-record-R = 75.6644
test_ordered-record-gold = 47601.0
test_ordered-record-pred = 51072.0
test_ordered-record-tp = 36017.0
test_overall-F1 = 73.0027
test_pred_tree = 51078
test_record-F1 = 73.0027
test_record-P = 70.522
test_record-R = 75.6644
test_record-gold = 47601.0
test_record-pred = 51072.0
test_record-tp = 36017.0
test_runtime = 2009.4985
test_samples_per_second = 18.735
test_spot-F1 = 73.0027
test_spot-P = 70.522
test_spot-R = 75.6644
test_spot-gold = 47601.0
test_spot-pred = 51072.0
test_spot-tp = 36017.0
test_steps_per_second = 0.586
test_well-formed = 37648
第二次推理得到的结果：
test_asoc-F1 = 0.0
test_asoc-P = 0.0
test_asoc-R = 0.0
test_asoc-gold = 0.0
test_asoc-pred = 0.0
test_asoc-tp = 0.0
test_fixed = 411
test_gen_len = 191.0
test_gold_tree = 56455
test_gold_tree add_bracket = 19
test_loss = 5.7737
test_ordered-record-F1 = 0.0
test_ordered-record-P = 0.0
test_ordered-record-R = 0.0
test_ordered-record-gold = 56447.0
test_ordered-record-pred = 105.0
test_ordered-record-tp = 0.0
test_overall-F1 = 0.0
test_pred_tree = 160719
test_record-F1 = 0.0
test_record-P = 0.0
test_record-R = 0.0
test_record-gold = 56447.0
test_record-pred = 105.0
test_record-tp = 0.0
test_runtime = 4370.3629
test_samples_per_second = 8.614
test_spot-F1 = 0.0
test_spot-P = 0.0
test_spot-R = 0.0
test_spot-gold = 56447.0
test_spot-pred = 105.0
test_spot-tp = 0.0
test_steps_per_second = 0.269
test_well-formed = 37648
（谢谢大佬🙏🙏🙏）

**Comment by guihonghao** [comment]
> 对于ACE2005这个数据集，得到的Event Trigger Evt Tri F1 和 Event Argument Evt Arg F1这两个 F1值分别对应的是什么呢？

Event Trigger Evt Tri F1是spot，Event Argument Evt Arg F1是asoc

**Comment by guihonghao** [comment]
训练时在prompt_conf中使用的export use_ssi=True
export use_prompt=True
export use_task=True
export prompt_len=80
export prompt_dim=800等参数要在推理的时候保持一致。还有output中会输出预测出的文件。看看模型的输是怎样的。

**Comment by 569337083** [comment]
在第一次模型训练和第二次模型推理的过程中，我没有修改conf文件，应该是保持一致的。
以下是预测的文件内容（命令：head test_preds_seq2seq.txt）：
<extra_id_0> person <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1>
<extra_id_0> person <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> award <extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1>
<extra_id_0> person <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1>  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  road  event  event  event  event  event  event  event  event  event  event  event
<extra_id_0> person <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1> <extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1>  person road  person road  person road  person road  person road  person road  person road  person road  person road  person road  person road  person road  person road  person road  person road  person  road <extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1><extra_id_1>
<extra_id_0> person <extra_id_1> <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1>  person <extra_id_1> road  person  event  event  event  event  event  event  event  event  event  event  event  event  event  event  person  person  person  person  person  person  person  person  person  person  person  person  person  person  event  event  event  event <extra_id_1>  event <extra_id_1> <extra_id_1> <extra_id_1>

**Comment by 569337083** [comment]
大佬，方便➕个 v or q 吗？

**Comment by 569337083** [comment]
是不是2-7次进行推理的时候用的以下这个命令：
. config/prompt_conf/ace05_event_H.ini
CUDA_VISIBLE_DEVICES=0 python3 eval/inference_mul.py --dataname=ace05_event --model=output/ace05_event_H_e30_lr1e-4_b16_n0.8_prompt_80_512 --task=event --cuda=0 --mode=H --use_ssi=${use_ssi} --use_task=${use_task} --use_prompt=${use_prompt} --prompt_len=${prompt_len} --prompt_dim=${prompt_dim}
而并非是我之前的用的命令：
. config/prompt_conf/ace05_event_H.ini  
bash scripts/run_finetune.bash --model=hf_models/t5-v1_1-base --data=data/ace05_event_H/iter_2 --output=output/ace05_event --mode=H --device=0 --batch=16
这里我用了和训练一样的命令，只不过换了data。

**Comment by guihonghao** [comment]
eval/inference_mul.py是自动推理2-7迭代，eval/inferencel.py是推理指定迭代数据集，你的指令--model=hf_models/t5-v1_1-base这里用的还是未训练的模型跑第二次迭代。

**Comment by 569337083** [comment]
在使用eval/inference_mul.py这个函数时，--t5_path这个参数默认的是hf_models/mix，而在训练的时候hf_models/t5_v1_1-base这个目录，这两个指的是一个目录吗？

**Comment by guihonghao** [comment]
. config/prompt_conf/ace05_event_H.ini
CUDA_VISIBLE_DEVICES=0 python3 eval/inference_mul.py --dataname=ace05_event --model=output/ace05_event_H_e30_lr1e-4_b16_n0.8_prompt_80_512 --task=event --cuda=0 --mode=H --use_ssi=${use_ssi} --use_task=${use_task} --use_prompt=${use_prompt} --prompt_len=${prompt_len} --prompt_dim=${prompt_dim}

model放训练后的模型

**Comment by 569337083** [comment]
我运行了以下命令，出现了报错：
. config/prompt_conf/NYT_H.ini 
CUDA_VISIBLE_DEVICES=2 python3 eval/inference_mul.py --dataname=NYT --model=output/NYT_H_e20_lr1e-4_b8_n1_prompt_50_800_task --task=relation --cuda=2 --mode=H --use_ssi=${use_ssi} --use_task=${use_task} --use_prompt=${use_prompt} --prompt_len=${prompt_len} --prompt_dim=${prompt_dim}

Traceback (most recent call last):
  File "eval/inference_mul.py", line 301, in <module>
    main()
  File "eval/inference_mul.py", line 203, in main
    predictor = HuggingfacePromptPredictor(args=options) 
  File "eval/inference_mul.py", line 67, in __init__
    self._model = T5Prompt(self._tokenizer, args.t5_path, args).to(self._device)
  File "/data/whs/projects/AdaKGC/./adakgc/models/models.py", line 47, in __init__
    self.t5 = T5ForConditionalGeneration.from_pretrained(model_name_or_path)
  File "/data/whs/miniconda/envs/adakgc/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1187, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/data/whs/miniconda/envs/adakgc/lib/python3.8/site-packages/transformers/configuration_utils.py", line 455, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/whs/miniconda/envs/adakgc/lib/python3.8/site-packages/transformers/configuration_utils.py", line 532, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'hf_models/mix'. Make sure that:

- 'hf_models/mix' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'hf_models/mix' is the correct path to a directory containing a config.json file

**Comment by 569337083** [comment]
我自己的项目中是没有这个目录的hf_models/mix，并且我的设备是链接不了hugging face的，这个是需要我自己下载吗？
在推理的过程的中多了一次并加了参数--CD ，想问一下这个作用是什么？
（感谢大佬）

**Comment by guihonghao** [comment]
--t5_path是T5模型hf_models/t5-v1_1-base，--model是训练后得到的模型。--CD 是约束解码

**Comment by guihonghao** [comment]
ghh200002你可以加我的微信
